node {
    checkout(scm)
    config = readYaml(file: "config.yaml")
    runtime_image = "${config.repository}/${config.runtime_image_name}:${config.runtime_image_tag}"
    branch_name = "master"

    System.setProperty("org.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS", "true") // for debugging

    stage('Test') {
        img = docker.image("${runtime_image}")
        img.inside {
            sh "pytest tests/data/ tests/model/"
        }
    }

    stage('Train Model') {

        echo(env.getEnvironment().collect({environmentVariable ->  "${environmentVariable.key} = ${environmentVariable.value}"}).join("\n"))
        echo(System.getenv().collect({environmentVariable ->  "${environmentVariable.key} = ${environmentVariable.value}"}).join("\n"))

        sh(script: "echo ${env}")

        // list all env variables 
        sh(script: 'env|sort', returnStdout: true)

        withDockerContainer(image: "${runtime_image}", args: "-u 0:0") {
            //sh "echo hello from container!"
            dir("jenkins/train-model") {
                sh "python3 train.py"
            }
            stash(name: "model", includes: "${config.model_path}/${config.model_name}")
        }
    }

    stage('Test Model') {
        echo sh(returnStdout: true, script: 'env')
        withDockerContainer(image: "${runtime_image}" ) {
            unstash(name: "model")
            dir("jenkins/train-model") {
                sh "python3 test.py"
            }
        }
    }

    stage('Push Model') {
        sh "echo Pushing the Model!"
        withCredentials([usernamePassword(credentialsId: "github" , usernameVariable: "USERNAME" , passwordVariable: "PASSWORD" )]) {
            sh "git config --global user.name 'jenkins'"
            sh "git config --global user.email 'jenkins@localhost'"

            sh "git checkout ${branch_name}" // solves: fatal: You are not currently on a branch.
            sh "git remote set-url origin https://${USERNAME}:${PASSWORD}@github.com/${USERNAME}/${config.github_project_name}.git" // solves: fatal: could not read Username for 'https://github.com': No such device or address 
            sh "git pull"    // solves: error: failed to push some refs to  ...
            unstash(name: "model")
            sh "git commit -am 'feat: re-train model (by jenkins)'"
            //sh "git push origin ${env.BRANCH_NAME}"
            sh "git push origin ${branch_name}"
        }
    }
}