apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment_name }}
  labels:
    app: {{ .Values.deployment_label }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment_label }}
    spec:
      containers:
      - name: {{ .Values.container_name }}
        image: {{ .Values.repository }}/{{ .Values.production_image_name }}:{{ .Values.production_image_tag }}
        ports:
        - containerPort: {{ .Values.container_port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
spec:
  type: {{ .Values.service_type }}
  selector:
    app: {{ .Values.deployment_label}}
  ports:
  - protocol: TCP
    port: {{ .Values.service_port }}
    nodePort: {{ .Values.service_node_port }}
