node {
    stage("checkout") {
        checkout(scm)
    }

    stage("get config variables") {
        config = readYaml(file: "config.yaml")
    }
}

node("k8s") {

    stage("Deploy to k8s") {
        withEnv(['PATH+EXTRA=/snap/bin']) {
            sh "jenkins/deploy/deployment.sh ${config.deployment_name} config.yaml"
        }
    }   
}
