---
repository: n02291 # Docker
registry: https://index.docker.io/v1/
docker_credentials_id: docker

runtime_image_name: ml_template_runtime_env
runtime_image_tag: 0.2.0

production_image_name: ml_template_production_env
production_image_tag: 0.0.1

docker_socket_path: "/var/run/docker.sock" # default linux path
model_path: "model_bin"
model_name: "model.pkl"

github_project_name: "machine-learning-microservice-template"

deployment_name: ml-template-deployment
...