node {
    def build_config = readYaml(file: "config/build.yaml")
}


pipeline{
    agent{
        label "master"
    }
    stages{
        stage("Echo") {
            steps {
                echo "${build_config}"
            }

        }
/*
        stage("Run Unit Tests"){
            agent {
                docker { image }
            }
            steps{
                echo "========Run Unit Tests========"

            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
        */
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}