node {
    //def build_config = readYaml(file: "config/build.yaml")
}


pipeline{
    agent{
        label "master"
    }
    stages{
        stage ("Load Build Configs") {
            steps {
                echo "========Load Build Configs========"
                script {
                    build_config = readYaml(file: "config/build.yaml")
                    echo "${build_config}"
                }
                echo "${build_config}"


            }
            environment {
                def runtime_image = "${build_config['docker_runtime_image_name']}:${build_config['docker_runtime_image_tag']}"
            }
        }

        stage("Run Unit Tests"){
            agent {
                docker { image ""
            }
            steps{
                echo "========Run Unit Tests========"

            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
        */
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}